server:
  port: 2000

spring:
  application:
    name: whw-crowd-mysql
  datasource:
    username: root
    password: 172161
    url: jdbc:mysql://localhost:3306/project_crowd?useUnicode=true&characterEndofing=UTF8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.whw.crowd.mapper: debug
    com.whw.crowd.test: debug

