server:
  port: 80

spring:
  application:
    name: whw-crowd-zuul
  redis:
    host: 192.168.130.172
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  add-host-header: true
  routes:
    crowd-portal:
      service-id: whw-crowd-auth
      path: /** #这里一定要写两个*号，表示多层目录
    crowd-project:
      service-id: whw-crowd-project
      path: /project/**
    crowd-order:
      service-id: whw-crowd-order
      path: /order/**
