server:
  port: 3000

spring:
  application:
    name: whw-crowd-redis
  redis:
    host: 192.168.130.172
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
